#!/bin/sh

usage()
{
    cat <<-EOF
	usage: ${0##*/} <command> [<param>[=<value]] ...
	
	commands and params may be tab-completed.
	if you install the \`highlight' program, output will be colored.
	EOF
    exit 1
}

[ $# -lt 1 ] && usage
[[ "$1" =~ --?h(elp)? ]] && usage

string=`echo $* |tr ' ' '&'`

url="http://localhost:8096/?command=$string"
output=`curl -s "$url"`

if [ -z "$output" ]
then
    echo "ERROR: Didn't receive expected data (is the port right?):"
    echo
    curl -v "$url"
    exit 1
else
    output=`echo $output | xmllint --format -`
fi

if [ -n "`which highlight 2>/dev/null`" ]
then
    echo "$output" | highlight -S xml -O ansi 
else
    echo "$output"
fi
